---
title: "Uber report"
author: "16F8347"
date: "12/12/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading libraries

```{r message=FALSE, warning=FALSE}
library(reticulate)
library(lubridate)
```

## Importing python modules
Used python to plot different density plots.

```{r message=FALSE, warning=FALSE}
use_python("C:\\Users\\shahz\\AppData\\Local\\Programs\\Python\\Python39\\python.exe")

sns <- import('seaborn')
pd <- import('pandas')
plt <- import('matplotlib.pyplot')

```

## Loading data

```{r message=FALSE, warning=FALSE}

data <- read.csv("uber.csv")
data$Date.Time <- as.Date(data$Date.Time, format = "%m/%d/%Y %H:%M:%S")
data$Day <- format(data$Date, format="%d")
data$weekday <- as.numeric(format(data$Date.Time, format = "%w"))
data$Hour <- format(data$Date, format="%H")

```

## Day density

```{r message=FALSE, warning=FALSE}
sns$distplot(data["Day"])
plt$show()
```
##Week Day Density
```{r message=FALSE, warning=FALSE}
sns$distplot(data["weekday"])
plt$show()
```

## Hour density

```{r message=FALSE, warning=FALSE}
plt$ylim(0, 1)
sns$distplot(data["Hour"])
plt$show()
```





